name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build (Release)
      run: cargo build --verbose --release
    - name: Run tests (Release)
      run: cargo test --verbose --release

  build-and-test-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build (Release)
      run: cargo build --verbose --release
    - name: Run tests (Release)
      run: cargo test --verbose --release
